In [1]:
import os
import polars as pl

In [ ]:
script_path = os.getcwd()
project_path = os.path.join(script_path, '..', '..', '..')
hashes_table_path = os.path.join(project_path, 'data', 'hashes', 'processed_data', 'hashes_groups.csv')

hashes_table = pl.read_csv(hashes_table_path, separator=';')

In [8]:
hashes_table

shape: (300, 3)
┌─────────────────┬─────────────────────┬──────────────┐
│ centro          ┆ id                  ┆ grupo        │
│ ---             ┆ ---                 ┆ ---          │
│ str             ┆ str                 ┆ str          │
╞═════════════════╪═════════════════════╪══════════════╡
│ JoseGarciaNieto ┆ JoseGarciaNieto-nnx ┆ control      │
│ JoseGarciaNieto ┆ JoseGarciaNieto-0w6 ┆ control      │
│ JoseGarciaNieto ┆ JoseGarciaNieto-2cv ┆ control      │
│ JoseGarciaNieto ┆ JoseGarciaNieto-kxj ┆ control      │
│ JoseGarciaNieto ┆ JoseGarciaNieto-hl3 ┆ control      │
│ …               ┆ …                   ┆ …            │
│ RamiroMaeztu    ┆ RamiroMaeztu-04b    ┆ experimental │
│ RamiroMaeztu    ┆ RamiroMaeztu-59v    ┆ experimental │
│ RamiroMaeztu    ┆ RamiroMaeztu-ip8    ┆ experimental │
│ RamiroMaeztu    ┆ RamiroMaeztu-hrf    ┆ experimental │
│ RamiroMaeztu    ┆ RamiroMaeztu-8jb    ┆ experimental │
└─────────────────┴─────────────────────┴──────────────┘

## Hashes-Groups Table by Centro

In [14]:
for centro in hashes_table['centro'].unique():
    print(f'\nHashes-Groups Table for Centro {centro}')
    with pl.Config(tbl_rows=-1):
        display(hashes_table.filter(pl.col('centro') == centro).select(['id', 'grupo']))

Hashes-Groups Table for Centro RamiroMaeztu

shape: (100, 2)
┌──────────────────┬──────────────┐
│ id               ┆ grupo        │
│ ---              ┆ ---          │
│ str              ┆ str          │
╞══════════════════╪══════════════╡
│ RamiroMaeztu-8q1 ┆ control      │
│ RamiroMaeztu-08k ┆ control      │
│ RamiroMaeztu-cpk ┆ control      │
│ RamiroMaeztu-djz ┆ control      │
│ RamiroMaeztu-406 ┆ control      │
│ RamiroMaeztu-ywi ┆ control      │
│ RamiroMaeztu-e6m ┆ control      │
│ RamiroMaeztu-gzv ┆ control      │
│ RamiroMaeztu-qzw ┆ control      │
│ RamiroMaeztu-zhk ┆ control      │
│ RamiroMaeztu-fe3 ┆ control      │
│ RamiroMaeztu-mw7 ┆ control      │
│ RamiroMaeztu-4gj ┆ control      │
│ RamiroMaeztu-hka ┆ control      │
│ RamiroMaeztu-lof ┆ control      │
│ RamiroMaeztu-a52 ┆ control      │
│ RamiroMaeztu-fmv ┆ control      │
│ RamiroMaeztu-st5 ┆ control      │
│ RamiroMaeztu-hju ┆ control      │
│ RamiroMaeztu-qjr ┆ control      │
│ RamiroMaeztu-scg ┆ control      │
│ RamiroMaeztu-p1m ┆ control      │
│ RamiroMaeztu-a7b ┆ control      │
│ RamiroMaeztu-wla ┆ control      │
│ RamiroMaeztu-9t2 ┆ control      │
│ RamiroMaeztu-u9m ┆ control      │
│ RamiroMaeztu-a95 ┆ control      │
│ RamiroMaeztu-fun ┆ control      │
│ RamiroMaeztu-wfn ┆ control      │
│ RamiroMaeztu-qhc ┆ control      │
│ RamiroMaeztu-ds6 ┆ control      │
│ RamiroMaeztu-4ux ┆ control      │
│ RamiroMaeztu-9nx ┆ control      │
│ RamiroMaeztu-byq ┆ control      │
│ RamiroMaeztu-j5g ┆ control      │
│ RamiroMaeztu-5lb ┆ control      │
│ RamiroMaeztu-lei ┆ control      │
│ RamiroMaeztu-fzz ┆ control      │
│ RamiroMaeztu-skl ┆ control      │
│ RamiroMaeztu-sdu ┆ control      │
│ RamiroMaeztu-mip ┆ control      │
│ RamiroMaeztu-5yc ┆ control      │
│ RamiroMaeztu-ikd ┆ control      │
│ RamiroMaeztu-irj ┆ control      │
│ RamiroMaeztu-sum ┆ control      │
│ RamiroMaeztu-f7p ┆ control      │
│ RamiroMaeztu-a28 ┆ control      │
│ RamiroMaeztu-y4p ┆ control      │
│ RamiroMaeztu-g49 ┆ control      │
│ RamiroMaeztu-6ba ┆ control      │
│ RamiroMaeztu-qr3 ┆ experimental │
│ RamiroMaeztu-g43 ┆ experimental │
│ RamiroMaeztu-h1h ┆ experimental │
│ RamiroMaeztu-b0n ┆ experimental │
│ RamiroMaeztu-t8e ┆ experimental │
│ RamiroMaeztu-pu9 ┆ experimental │
│ RamiroMaeztu-ks0 ┆ experimental │
│ RamiroMaeztu-8pr ┆ experimental │
│ RamiroMaeztu-kya ┆ experimental │
│ RamiroMaeztu-7c5 ┆ experimental │
│ RamiroMaeztu-s1e ┆ experimental │
│ RamiroMaeztu-ykt ┆ experimental │
│ RamiroMaeztu-ktr ┆ experimental │
│ RamiroMaeztu-2kk ┆ experimental │
│ RamiroMaeztu-j32 ┆ experimental │
│ RamiroMaeztu-0ad ┆ experimental │
│ RamiroMaeztu-39p ┆ experimental │
│ RamiroMaeztu-o8s ┆ experimental │
│ RamiroMaeztu-kcz ┆ experimental │
│ RamiroMaeztu-bzv ┆ experimental │
│ RamiroMaeztu-0o0 ┆ experimental │
│ RamiroMaeztu-2rr ┆ experimental │
│ RamiroMaeztu-9sx ┆ experimental │
│ RamiroMaeztu-qf2 ┆ experimental │
│ RamiroMaeztu-dpu ┆ experimental │
│ RamiroMaeztu-31d ┆ experimental │
│ RamiroMaeztu-8l8 ┆ experimental │
│ RamiroMaeztu-fc1 ┆ experimental │
│ RamiroMaeztu-ycb ┆ experimental │
│ RamiroMaeztu-qf6 ┆ experimental │
│ RamiroMaeztu-5p9 ┆ experimental │
│ RamiroMaeztu-4bc ┆ experimental │
│ RamiroMaeztu-2xu ┆ experimental │
│ RamiroMaeztu-x5e ┆ experimental │
│ RamiroMaeztu-404 ┆ experimental │
│ RamiroMaeztu-86g ┆ experimental │
│ RamiroMaeztu-wr6 ┆ experimental │
│ RamiroMaeztu-9jg ┆ experimental │
│ RamiroMaeztu-80a ┆ experimental │
│ RamiroMaeztu-b5f ┆ experimental │
│ RamiroMaeztu-h3l ┆ experimental │
│ RamiroMaeztu-unc ┆ experimental │
│ RamiroMaeztu-hrb ┆ experimental │
│ RamiroMaeztu-z2k ┆ experimental │
│ RamiroMaeztu-kp3 ┆ experimental │
│ RamiroMaeztu-04b ┆ experimental │
│ RamiroMaeztu-59v ┆ experimental │
│ RamiroMaeztu-ip8 ┆ experimental │
│ RamiroMaeztu-hrf ┆ experimental │
│ RamiroMaeztu-8jb ┆ experimental │
└──────────────────┴──────────────┘

Hashes-Groups Table for Centro JesusMaria

shape: (100, 2)
┌────────────────┬──────────────┐
│ id             ┆ grupo        │
│ ---            ┆ ---          │
│ str            ┆ str          │
╞════════════════╪══════════════╡
│ JesusMaria-64o ┆ control      │
│ JesusMaria-bbc ┆ control      │
│ JesusMaria-shf ┆ control      │
│ JesusMaria-l57 ┆ control      │
│ JesusMaria-tim ┆ control      │
│ JesusMaria-hq8 ┆ control      │
│ JesusMaria-m9b ┆ control      │
│ JesusMaria-3pk ┆ control      │
│ JesusMaria-4td ┆ control      │
│ JesusMaria-hrs ┆ control      │
│ JesusMaria-s5p ┆ control      │
│ JesusMaria-ub4 ┆ control      │
│ JesusMaria-86o ┆ control      │
│ JesusMaria-ug8 ┆ control      │
│ JesusMaria-7u7 ┆ control      │
│ JesusMaria-6vh ┆ control      │
│ JesusMaria-m31 ┆ control      │
│ JesusMaria-osd ┆ control      │
│ JesusMaria-ldh ┆ control      │
│ JesusMaria-o95 ┆ control      │
│ JesusMaria-f7r ┆ control      │
│ JesusMaria-s17 ┆ control      │
│ JesusMaria-szt ┆ control      │
│ JesusMaria-ayb ┆ control      │
│ JesusMaria-yxb ┆ control      │
│ JesusMaria-8vw ┆ control      │
│ JesusMaria-hs2 ┆ control      │
│ JesusMaria-1qm ┆ control      │
│ JesusMaria-1xj ┆ control      │
│ JesusMaria-m40 ┆ control      │
│ JesusMaria-i04 ┆ control      │
│ JesusMaria-byl ┆ control      │
│ JesusMaria-po1 ┆ control      │
│ JesusMaria-l21 ┆ control      │
│ JesusMaria-a65 ┆ control      │
│ JesusMaria-a6g ┆ control      │
│ JesusMaria-y6s ┆ control      │
│ JesusMaria-o05 ┆ control      │
│ JesusMaria-wmk ┆ control      │
│ JesusMaria-e34 ┆ control      │
│ JesusMaria-xcg ┆ control      │
│ JesusMaria-fjf ┆ control      │
│ JesusMaria-lhd ┆ control      │
│ JesusMaria-exk ┆ control      │
│ JesusMaria-y2l ┆ control      │
│ JesusMaria-wbe ┆ control      │
│ JesusMaria-0h7 ┆ control      │
│ JesusMaria-r73 ┆ control      │
│ JesusMaria-fxv ┆ control      │
│ JesusMaria-ecq ┆ control      │
│ JesusMaria-d21 ┆ experimental │
│ JesusMaria-zoj ┆ experimental │
│ JesusMaria-p5x ┆ experimental │
│ JesusMaria-aue ┆ experimental │
│ JesusMaria-40a ┆ experimental │
│ JesusMaria-f16 ┆ experimental │
│ JesusMaria-siq ┆ experimental │
│ JesusMaria-2zu ┆ experimental │
│ JesusMaria-bbo ┆ experimental │
│ JesusMaria-6in ┆ experimental │
│ JesusMaria-3ci ┆ experimental │
│ JesusMaria-2b0 ┆ experimental │
│ JesusMaria-nre ┆ experimental │
│ JesusMaria-xpe ┆ experimental │
│ JesusMaria-f00 ┆ experimental │
│ JesusMaria-jxz ┆ experimental │
│ JesusMaria-am7 ┆ experimental │
│ JesusMaria-3t5 ┆ experimental │
│ JesusMaria-yi0 ┆ experimental │
│ JesusMaria-2fa ┆ experimental │
│ JesusMaria-1lv ┆ experimental │
│ JesusMaria-5mz ┆ experimental │
│ JesusMaria-nms ┆ experimental │
│ JesusMaria-4q4 ┆ experimental │
│ JesusMaria-hem ┆ experimental │
│ JesusMaria-33y ┆ experimental │
│ JesusMaria-r7e ┆ experimental │
│ JesusMaria-4e6 ┆ experimental │
│ JesusMaria-iff ┆ experimental │
│ JesusMaria-d01 ┆ experimental │
│ JesusMaria-f6g ┆ experimental │
│ JesusMaria-79x ┆ experimental │
│ JesusMaria-22s ┆ experimental │
│ JesusMaria-6es ┆ experimental │
│ JesusMaria-o8r ┆ experimental │
│ JesusMaria-kio ┆ experimental │
│ JesusMaria-366 ┆ experimental │
│ JesusMaria-v74 ┆ experimental │
│ JesusMaria-lx7 ┆ experimental │
│ JesusMaria-hbu ┆ experimental │
│ JesusMaria-ntg ┆ experimental │
│ JesusMaria-udl ┆ experimental │
│ JesusMaria-cnx ┆ experimental │
│ JesusMaria-6j9 ┆ experimental │
│ JesusMaria-g16 ┆ experimental │
│ JesusMaria-tpy ┆ experimental │
│ JesusMaria-7ci ┆ experimental │
│ JesusMaria-5fk ┆ experimental │
│ JesusMaria-6hg ┆ experimental │
│ JesusMaria-xed ┆ experimental │
└────────────────┴──────────────┘

Hashes-Groups Table for Centro JoseGarciaNieto

shape: (100, 2)
┌─────────────────────┬──────────────┐
│ id                  ┆ grupo        │
│ ---                 ┆ ---          │
│ str                 ┆ str          │
╞═════════════════════╪══════════════╡
│ JoseGarciaNieto-nnx ┆ control      │
│ JoseGarciaNieto-0w6 ┆ control      │
│ JoseGarciaNieto-2cv ┆ control      │
│ JoseGarciaNieto-kxj ┆ control      │
│ JoseGarciaNieto-hl3 ┆ control      │
│ JoseGarciaNieto-loj ┆ control      │
│ JoseGarciaNieto-a4v ┆ control      │
│ JoseGarciaNieto-gvd ┆ control      │
│ JoseGarciaNieto-6py ┆ control      │
│ JoseGarciaNieto-4w9 ┆ control      │
│ JoseGarciaNieto-15y ┆ control      │
│ JoseGarciaNieto-9ba ┆ control      │
│ JoseGarciaNieto-c44 ┆ control      │
│ JoseGarciaNieto-orj ┆ control      │
│ JoseGarciaNieto-3q1 ┆ control      │
│ JoseGarciaNieto-hoe ┆ control      │
│ JoseGarciaNieto-np6 ┆ control      │
│ JoseGarciaNieto-gks ┆ control      │
│ JoseGarciaNieto-pck ┆ control      │
│ JoseGarciaNieto-od5 ┆ control      │
│ JoseGarciaNieto-a1y ┆ control      │
│ JoseGarciaNieto-2or ┆ control      │
│ JoseGarciaNieto-1m9 ┆ control      │
│ JoseGarciaNieto-033 ┆ control      │
│ JoseGarciaNieto-wq6 ┆ control      │
│ JoseGarciaNieto-wba ┆ control      │
│ JoseGarciaNieto-jhk ┆ control      │
│ JoseGarciaNieto-t3r ┆ control      │
│ JoseGarciaNieto-r80 ┆ control      │
│ JoseGarciaNieto-eod ┆ control      │
│ JoseGarciaNieto-6cx ┆ control      │
│ JoseGarciaNieto-fnb ┆ control      │
│ JoseGarciaNieto-i84 ┆ control      │
│ JoseGarciaNieto-eu2 ┆ control      │
│ JoseGarciaNieto-4i2 ┆ control      │
│ JoseGarciaNieto-5r5 ┆ control      │
│ JoseGarciaNieto-baj ┆ control      │
│ JoseGarciaNieto-qx5 ┆ control      │
│ JoseGarciaNieto-t6q ┆ control      │
│ JoseGarciaNieto-h2j ┆ control      │
│ JoseGarciaNieto-8k0 ┆ control      │
│ JoseGarciaNieto-zyl ┆ control      │
│ JoseGarciaNieto-ywb ┆ control      │
│ JoseGarciaNieto-as2 ┆ control      │
│ JoseGarciaNieto-2tk ┆ control      │
│ JoseGarciaNieto-lp9 ┆ control      │
│ JoseGarciaNieto-r6z ┆ control      │
│ JoseGarciaNieto-dh0 ┆ control      │
│ JoseGarciaNieto-yfp ┆ control      │
│ JoseGarciaNieto-y6x ┆ control      │
│ JoseGarciaNieto-uy6 ┆ experimental │
│ JoseGarciaNieto-yk4 ┆ experimental │
│ JoseGarciaNieto-5zg ┆ experimental │
│ JoseGarciaNieto-k69 ┆ experimental │
│ JoseGarciaNieto-1uv ┆ experimental │
│ JoseGarciaNieto-m36 ┆ experimental │
│ JoseGarciaNieto-ois ┆ experimental │
│ JoseGarciaNieto-pt3 ┆ experimental │
│ JoseGarciaNieto-sp1 ┆ experimental │
│ JoseGarciaNieto-3se ┆ experimental │
│ JoseGarciaNieto-2u0 ┆ experimental │
│ JoseGarciaNieto-ca9 ┆ experimental │
│ JoseGarciaNieto-art ┆ experimental │
│ JoseGarciaNieto-imz ┆ experimental │
│ JoseGarciaNieto-rcu ┆ experimental │
│ JoseGarciaNieto-o6z ┆ experimental │
│ JoseGarciaNieto-r6j ┆ experimental │
│ JoseGarciaNieto-p5c ┆ experimental │
│ JoseGarciaNieto-78x ┆ experimental │
│ JoseGarciaNieto-euw ┆ experimental │
│ JoseGarciaNieto-wob ┆ experimental │
│ JoseGarciaNieto-e7f ┆ experimental │
│ JoseGarciaNieto-sic ┆ experimental │
│ JoseGarciaNieto-i3f ┆ experimental │
│ JoseGarciaNieto-ivs ┆ experimental │
│ JoseGarciaNieto-9kf ┆ experimental │
│ JoseGarciaNieto-wxc ┆ experimental │
│ JoseGarciaNieto-71b ┆ experimental │
│ JoseGarciaNieto-ual ┆ experimental │
│ JoseGarciaNieto-lex ┆ experimental │
│ JoseGarciaNieto-qqe ┆ experimental │
│ JoseGarciaNieto-7sg ┆ experimental │
│ JoseGarciaNieto-ed5 ┆ experimental │
│ JoseGarciaNieto-zvb ┆ experimental │
│ JoseGarciaNieto-i3u ┆ experimental │
│ JoseGarciaNieto-j3a ┆ experimental │
│ JoseGarciaNieto-hmq ┆ experimental │
│ JoseGarciaNieto-8vr ┆ experimental │
│ JoseGarciaNieto-q65 ┆ experimental │
│ JoseGarciaNieto-2ah ┆ experimental │
│ JoseGarciaNieto-411 ┆ experimental │
│ JoseGarciaNieto-9qn ┆ experimental │
│ JoseGarciaNieto-ma7 ┆ experimental │
│ JoseGarciaNieto-ohi ┆ experimental │
│ JoseGarciaNieto-rwf ┆ experimental │
│ JoseGarciaNieto-yhk ┆ experimental │
│ JoseGarciaNieto-qi0 ┆ experimental │
│ JoseGarciaNieto-ukt ┆ experimental │
│ JoseGarciaNieto-s1c ┆ experimental │
│ JoseGarciaNieto-ee5 ┆ experimental │
└─────────────────────┴──────────────┘

## Get Group for a given ID

In [17]:
ID = 'RamiroMaeztu-hrf'

hashes_table.filter(pl.col('id') == ID)['grupo'][0]

'experimental'