In [1]:
import os
import polars as pl

In [ ]:
script_path = os.getcwd()
project_path = os.path.join(script_path, '..', '..', '..')
hashes_table_path = os.path.join(project_path, 'data', 'hashes', 'processed_data', 'hashes_groups.csv')

hashes_table = pl.read_csv(hashes_table_path, separator=';')

In [8]:
hashes_table

shape: (300, 3)
┌─────────────────┬─────────────────────┬──────────────┐
│ centro          ┆ id                  ┆ grupo        │
│ ---             ┆ ---                 ┆ ---          │
│ str             ┆ str                 ┆ str          │
╞═════════════════╪═════════════════════╪══════════════╡
│ JoseGarciaNieto ┆ JoseGarciaNieto-nnx ┆ control      │
│ JoseGarciaNieto ┆ JoseGarciaNieto-0w6 ┆ control      │
│ JoseGarciaNieto ┆ JoseGarciaNieto-2cv ┆ control      │
│ JoseGarciaNieto ┆ JoseGarciaNieto-kxj ┆ control      │
│ JoseGarciaNieto ┆ JoseGarciaNieto-hl3 ┆ control      │
│ …               ┆ …                   ┆ …            │
│ RamiroMaeztu    ┆ RamiroMaeztu-04b    ┆ experimental │
│ RamiroMaeztu    ┆ RamiroMaeztu-59v    ┆ experimental │
│ RamiroMaeztu    ┆ RamiroMaeztu-ip8    ┆ experimental │
│ RamiroMaeztu    ┆ RamiroMaeztu-hrf    ┆ experimental │
│ RamiroMaeztu    ┆ RamiroMaeztu-8jb    ┆ experimental │
└─────────────────┴─────────────────────┴──────────────┘

In [11]:
with pl.Config(tbl_rows=-1):
    display(hashes_table.filter(pl.col('centro') == 'RamiroMaeztu').select(['id', 'grupo']))

shape: (100, 2)
┌──────────────────┬──────────────┐
│ id               ┆ grupo        │
│ ---              ┆ ---          │
│ str              ┆ str          │
╞══════════════════╪══════════════╡
│ RamiroMaeztu-8q1 ┆ control      │
│ RamiroMaeztu-08k ┆ control      │
│ RamiroMaeztu-cpk ┆ control      │
│ RamiroMaeztu-djz ┆ control      │
│ RamiroMaeztu-406 ┆ control      │
│ RamiroMaeztu-ywi ┆ control      │
│ RamiroMaeztu-e6m ┆ control      │
│ RamiroMaeztu-gzv ┆ control      │
│ RamiroMaeztu-qzw ┆ control      │
│ RamiroMaeztu-zhk ┆ control      │
│ RamiroMaeztu-fe3 ┆ control      │
│ RamiroMaeztu-mw7 ┆ control      │
│ RamiroMaeztu-4gj ┆ control      │
│ RamiroMaeztu-hka ┆ control      │
│ RamiroMaeztu-lof ┆ control      │
│ RamiroMaeztu-a52 ┆ control      │
│ RamiroMaeztu-fmv ┆ control      │
│ RamiroMaeztu-st5 ┆ control      │
│ RamiroMaeztu-hju ┆ control      │
│ RamiroMaeztu-qjr ┆ control      │
│ RamiroMaeztu-scg ┆ control      │
│ RamiroMaeztu-p1m ┆ control      │
│ RamiroMaeztu-a7b ┆ control      │
│ RamiroMaeztu-wla ┆ control      │
│ RamiroMaeztu-9t2 ┆ control      │
│ RamiroMaeztu-u9m ┆ control      │
│ RamiroMaeztu-a95 ┆ control      │
│ RamiroMaeztu-fun ┆ control      │
│ RamiroMaeztu-wfn ┆ control      │
│ RamiroMaeztu-qhc ┆ control      │
│ RamiroMaeztu-ds6 ┆ control      │
│ RamiroMaeztu-4ux ┆ control      │
│ RamiroMaeztu-9nx ┆ control      │
│ RamiroMaeztu-byq ┆ control      │
│ RamiroMaeztu-j5g ┆ control      │
│ RamiroMaeztu-5lb ┆ control      │
│ RamiroMaeztu-lei ┆ control      │
│ RamiroMaeztu-fzz ┆ control      │
│ RamiroMaeztu-skl ┆ control      │
│ RamiroMaeztu-sdu ┆ control      │
│ RamiroMaeztu-mip ┆ control      │
│ RamiroMaeztu-5yc ┆ control      │
│ RamiroMaeztu-ikd ┆ control      │
│ RamiroMaeztu-irj ┆ control      │
│ RamiroMaeztu-sum ┆ control      │
│ RamiroMaeztu-f7p ┆ control      │
│ RamiroMaeztu-a28 ┆ control      │
│ RamiroMaeztu-y4p ┆ control      │
│ RamiroMaeztu-g49 ┆ control      │
│ RamiroMaeztu-6ba ┆ control      │
│ RamiroMaeztu-qr3 ┆ experimental │
│ RamiroMaeztu-g43 ┆ experimental │
│ RamiroMaeztu-h1h ┆ experimental │
│ RamiroMaeztu-b0n ┆ experimental │
│ RamiroMaeztu-t8e ┆ experimental │
│ RamiroMaeztu-pu9 ┆ experimental │
│ RamiroMaeztu-ks0 ┆ experimental │
│ RamiroMaeztu-8pr ┆ experimental │
│ RamiroMaeztu-kya ┆ experimental │
│ RamiroMaeztu-7c5 ┆ experimental │
│ RamiroMaeztu-s1e ┆ experimental │
│ RamiroMaeztu-ykt ┆ experimental │
│ RamiroMaeztu-ktr ┆ experimental │
│ RamiroMaeztu-2kk ┆ experimental │
│ RamiroMaeztu-j32 ┆ experimental │
│ RamiroMaeztu-0ad ┆ experimental │
│ RamiroMaeztu-39p ┆ experimental │
│ RamiroMaeztu-o8s ┆ experimental │
│ RamiroMaeztu-kcz ┆ experimental │
│ RamiroMaeztu-bzv ┆ experimental │
│ RamiroMaeztu-0o0 ┆ experimental │
│ RamiroMaeztu-2rr ┆ experimental │
│ RamiroMaeztu-9sx ┆ experimental │
│ RamiroMaeztu-qf2 ┆ experimental │
│ RamiroMaeztu-dpu ┆ experimental │
│ RamiroMaeztu-31d ┆ experimental │
│ RamiroMaeztu-8l8 ┆ experimental │
│ RamiroMaeztu-fc1 ┆ experimental │
│ RamiroMaeztu-ycb ┆ experimental │
│ RamiroMaeztu-qf6 ┆ experimental │
│ RamiroMaeztu-5p9 ┆ experimental │
│ RamiroMaeztu-4bc ┆ experimental │
│ RamiroMaeztu-2xu ┆ experimental │
│ RamiroMaeztu-x5e ┆ experimental │
│ RamiroMaeztu-404 ┆ experimental │
│ RamiroMaeztu-86g ┆ experimental │
│ RamiroMaeztu-wr6 ┆ experimental │
│ RamiroMaeztu-9jg ┆ experimental │
│ RamiroMaeztu-80a ┆ experimental │
│ RamiroMaeztu-b5f ┆ experimental │
│ RamiroMaeztu-h3l ┆ experimental │
│ RamiroMaeztu-unc ┆ experimental │
│ RamiroMaeztu-hrb ┆ experimental │
│ RamiroMaeztu-z2k ┆ experimental │
│ RamiroMaeztu-kp3 ┆ experimental │
│ RamiroMaeztu-04b ┆ experimental │
│ RamiroMaeztu-59v ┆ experimental │
│ RamiroMaeztu-ip8 ┆ experimental │
│ RamiroMaeztu-hrf ┆ experimental │
│ RamiroMaeztu-8jb ┆ experimental │
└──────────────────┴──────────────┘